spring:
  datasource:
    url: jdbc:mysql://localhost/pan-api?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 600000       # 连接最大存活时间 10 分钟
      idle-timeout: 300000        # 空闲连接的最大存活时间 5 分钟
      keepalive-time: 60000      # 1 分钟发心跳包，避免被踢

jwt:
  secret: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMDEiLCJpYXQiOjE3NjgzNjg0MzMsImV4cCI6MTc2OTY2NDQzM30.aVOQi2_Ea8IuBpKvYzIyxxnMq5KeemZ6bpMRIkm_v0k
